name: nexus_voice_assistant
description: A Flutter app that records audio and sends it to OpenAI Realtime API
publish_to: 'none'
version: 1.0.21+21

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  openai_realtime_dart: ^0.1.0
  permission_handler: ^12.0.1
  record: ^6.1.2
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.6
  opus_dart: ^3.0.1
  opus_flutter: ^3.0.3
  # Web-specific dependencies
  universal_html: ^2.3.0
  share_plus: ^12.0.1
  platform_info: ^5.0.0
  audioplayers: ^6.0.0
  http: ^1.6.0
  flutter_dotenv: ^6.0.0
  flutter_blue_plus: ^2.1.0
  flutter_background_service: ^5.0.5
  # Navigator dependencies
  flutter_riverpod: ^3.2.0
  riverpod: ^3.2.0
  go_router: ^17.0.1
  graphql_flutter: ^5.1.2
  graphql: ^5.1.1
  json_annotation: ^4.9.0
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/s16le_16000hz_mono.raw
    - assets/download.js
    - assets/ai.opus
    - .env
