name: nexus_voice_assistant
description: A Flutter app that records audio and sends it to OpenAI Realtime API
publish_to: 'none'
version: 1.0.12+12

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  openai_realtime_dart: ^0.1.0
  permission_handler: ^12.0.1
  record: ^6.1.2
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.6
  opus_dart: ^3.0.1
  opus_flutter: ^3.0.3
  # Web-specific dependencies
  universal_html: ^2.2.4
  share_plus: ^7.2.1
  platform_info: ^4.0.2
  audioplayers: ^6.0.0
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  flutter_blue_plus: ^1.31.7
  flutter_background_service: ^5.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/s16le_16000hz_mono.raw
    - assets/download.js
    - .env
